INSERT INTO DomainName VALUE ('bad.com')
INSERT INTO DomainName VALUE ('good.com')
INSERT INTO IpAddress VALUE ('1.2.3.4')
INSERT INTO IpAddress VALUE ('1.2.3.5')
INSERT INTO InfoSource VALUE (1, 'GeorgieSource')
INSERT INTO Resolution (1, 'bad.com', '1.2.3.4', 1)